version: '3'

services:
  hausl_bot:
    container_name: hausl_bot
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      - BOT_TOKEN
      - WARN_CELL_ID